name: Cross-compile for sparc64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-sparc64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install sparc64 cross compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-sparc64-linux-gnu

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: sparc64-unknown-linux-gnu
      - name: Build STD LIB
        run: cargo build --Zbuild std
      - name: Build project for sparc64
        run: cargo build --release --target=sparc64-unknown-linux-gnu

      - name: Create build directory and copy binary
        run: |
          mkdir -p build
          cp target/sparc64-unknown-linux-gnu/release/* build/ || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sparc64-binary
          path: build/
